name 'observium'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures observium'
long_description 'Installs/Configures observium'
version '0.1.0'

depends 'yum', '~> 3.8.2'
depends 'apt', '~> 2.9.2'
depends 'mysql2_chef_gem', '~> 1.0.1'
depends 'mysql', '~> 6.1.2'
depends 'database', '~> 4.0.9'
depends 'selinux', '~> 0.9.0'
depends 'cron', '~> 1.7.0'
# depends 'firewall', '~> 2.2.0'
